table transacoes
	lineageTag: bb5f1e1e-9f8c-4986-a314-34f111ebe8be

	measure 'Valor Total' = SUM(transacoes[Total])
		displayFolder: Medidas
		lineageTag: 1c1fa97a-bd08-4fbd-84ac-1d85dc0f4309

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cotação corrigida' = ```
			
			
			VAR __DataCtx = MAX(calendario[Data]) 
			
			VAR __UltimaDataComCotacao = 
			    CALCULATE(
			        LASTNONBLANK(calendario[Data], [Cotação do dia]),
			        calendario[Data] <= __DataCtx
			    )
			
			RETURN
			    CALCULATE(
			        [Cotação do dia],
			        calendario[Data] = __UltimaDataComCotacao
			    )
			```
		displayFolder: Medidas
		lineageTag: dcd0c6d2-0190-44e4-aed5-a6a2f7a1904e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total R$' = ```
			
			SUMX(
			    moedas,
			    SUMX(
			        calendario,
			        COALESCE([Cotação corrigida], 1) * [Valor Total] 
			    )
			)
			```
		displayFolder: Medidas
		lineageTag: 79a19354-c0d9-49fc-8729-cd6ce5e07deb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID
		dataType: double
		displayFolder: Colunas
		lineageTag: 577540ba-3794-4f7e-a2a7-3311de3948bf
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Data
		dataType: dateTime
		formatString: Short Date
		displayFolder: Colunas
		lineageTag: f32486ca-c5d0-407c-a546-2581441e55bf
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Total
		dataType: double
		displayFolder: Colunas
		lineageTag: 0dc95c78-470b-469f-a335-d92757b8065f
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Moeda
		dataType: string
		displayFolder: Colunas
		lineageTag: fbcd85b0-b762-4c1e-968f-51369f54a418
		summarizeBy: none
		sourceColumn: Moeda

		annotation SummarizationSetBy = Automatic

	partition transacoes = m
		mode: import
		queryGroup: Fatos
		source = ```
				let
				    source = Excel.Workbook(
				        File.Contents(base_transacoes), 
				        true, 
				        null
				    ),
				    
				    transacoes_Table = source{[Item="transacoes",Kind="Table"]}[Data],
				    
				    datesRestricted = Table.SelectRows(
				        transacoes_Table, 
				        each [Data] >= data_inicial and [Data] <= data_final
				    )
				in
				    datesRestricted
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

